
const app= new Vue({
    el:'#app',
    data:{
        books:[
            {
                id:1,
                name:'shuihu',
                date:'2010-9',
                price:85.00,
                count:1
            },
            {
                id:1,
                name:'hongloumeng',
                date:'2000-10',
                price:100.00,
                count:3
            },
            {
                id:1,
                name:'xiyouji',
                date:'2040-9',
                price:100.00,
                count:5
            },
            {
                id:1,
                name:'sanguo',
                date:'2054-10',
                price:85.00,
                count:7
            },
        ]
    }
});
